services:
  db1:
    image: postgres:16
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5442:5432'
    volumes:
      - postgres-data_userSvc:/var/lib/postgresql/data
  db2:
    image: postgres:16
    environment:
      POSTGRES_DB: authentication_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5443:5432'
    volumes:
      - postgres-data_authSvc:/var/lib/postgresql/data
  db3:
    image: postgres:16
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5444:5432'
    volumes:
      - postgres-data_orderSvc:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6378:6379'

  app1:
    image: ghcr.io/kruartspqr/userservice_docker_image:latest
    depends_on:
      - db1
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db1:5432/user_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - '8081:8081'
    restart: unless-stopped

  app2:
    image: ghcr.io/kruartspqr/authservice_docker_image:latest
    depends_on:
      - db2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db2:5432/authentication_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    ports:
      - '8082:8082'
    restart: unless-stopped
  app3:
    image: ghcr.io/kruartspqr/orderservice_docker_image:latest
    depends_on:
      - db3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db3:5432/order_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    ports:
      - '8083:8083'
    restart: unless-stopped

  app4:
    image: ghcr.io/kruartspqr/apigateway_docker_image:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - app1
      - app2
      - app3

    ports:
      - '8080:8080'

    restart: unless-stopped

volumes:
  postgres-data_userSvc:
  postgres-data_authSvc:
  postgres-data_orderSvc: