spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=Debug, true
  profiles:
    active: dev

jwt:
  secretKey: A4E12v8ZEiv9VNmDyipTJlZyhnPJS3ZH7Rd4ANcMkANU9t0fZ7TXh66qL2I=

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    org.springframework.http: DEBUG
    org.springframework.web.server: TRACE
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG

userServiceAddress: http://localhost:8081
authServiceAddress: http://localhost:8082
orderServiceAddress: http://localhost:8083
paymentServiceAddress: http://localhost:8084

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
userServiceAddress: http://app1:8081
authServiceAddress: http://app2:8082
orderServiceAddress: http://app3:8083
paymentServiceAddress: http://app4:8084
  
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info